@echo off
:: ============================================================================
:: UberStrike 4.3 Compatible Compiler Script
:: Generated by Gemini CLI for local environment
:: ============================================================================

set GAME_MANAGED_PATH="C:\Users\Shadow\Desktop\Photon-research\UberClient-4.8.3\UberStrike_Data\Managed"
set OUTPUT=UberStrikeBots_Compatible.dll
set CSC="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"

echo ==================================================
echo COMPILING FOR UBERSTRIKE 4.3 (Unity Legacy)
echo Target Path: %GAME_MANAGED_PATH%
echo ==================================================

cd UnityIntegration

%CSC% /target:library /out:..\%OUTPUT% ^
    /reference:%GAME_MANAGED_PATH%\UnityEngine.dll ^
    /platform:x86 ^
    /optimize- ^
    /debug+ ^
    /langversion:3 ^
    /define:UNITY_2017 ^
    BotInjector.cs BotController.cs InjectionTester.cs PracticeModeDetector.cs LocalSimulationManager.cs VersionDetector.cs InputEmulator.cs BotMetrics.cs ReflectionProbe.cs BotTestingHarness.cs

if %errorlevel% equ 0 (
    echo.
    echo ✅ SUCCESS! Created: %OUTPUT%
    echo Use this DLL for injection into your UberStrike client.
) else (
    echo.
    echo ❌ COMPILATION FAILED!
    echo Check for missing references or assembly mismatches.
)
pause
