#!/bin/bash
set -euo pipefail

PROJECT="BotRunner"
DETERMINISM_SCENARIO="flipping_regression"
PERF_SCENARIOS=(duel many_actors load_spike_test bad_payload flipping_test flipping_regression state_integrity_test swarm_retreat_test spawn_wave weapon_test ammo_pressure moving_target shoot_window_test team_duel loop respawn_loop regression_suite deterministic_suite reorder_drop bad_payload)
VALIDATION_REPORT="validation-report.json"
QUIET_FLAG="--quiet"

make_hash() {
  if command -v md5sum >/dev/null; then
    md5sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

determinism_pass=true
determinism_results=()

for seed in $(seq 1 100); do
  tmp="$(mktemp)"
  for run in 1 2; do
    dotnet run --project "${PROJECT}" -- --scenario "${DETERMINISM_SCENARIO}" --seed "${seed}" ${QUIET_FLAG} >/dev/null
    if [ ! -f run-summary.json ]; then determinism_pass=false; break; fi
    make_hash run-summary.json >>"${tmp}"
  done
  if [ "$determinism_pass" = false ]; then
    determinism_results+=("{\"seed\":${seed},\"pass\":false}")
    rm -f "${tmp}"
    break
  fi
  unique=$(sort "${tmp}" | uniq | wc -l)
  pass_seed=$([ "$unique" -eq 1 ] && echo true || echo false)
  determinism_results+=("{\"seed\":${seed},\"pass\":${pass_seed}}")
  if [ "$pass_seed" = false ]; then determinism_pass=false; fi
  rm -f "${tmp}"
 done

perf_rows=()
decision_conf_total=0
decision_conf_count=0
for scenario in "${PERF_SCENARIOS[@]}"; do
  time_out="$(mktemp)"
  /usr/bin/time -f "%e %M" -o "${time_out}" dotnet run --project "${PROJECT}" -- --scenario "${scenario}" --seed 1 ${QUIET_FLAG} >/dev/null || true
  read -r time_val mem_kb <"${time_out}"
  mem_mb=$(python - <<PY
import sys
try:
    kb=float(sys.argv[1])
    print(round(kb/1024,2))
except Exception:
    print(0)
PY
${mem_kb})
  avg_conf=$(jq -r '.ActionPipeline.AvgDecisionConfidence // 0' run-summary.json 2>/dev/null || echo 0)
  perf_rows+=("{\"scenario\":\"${scenario}\",\"time_sec\":${time_val:-0},\"peak_mem_mb\":${mem_mb:-0},\"avg_confidence\":${avg_conf:-0}}")
  decision_conf_total=$(python - <<PY
import sys
print(float(sys.argv[1]) + float(sys.argv[2]))
PY
${decision_conf_total} ${avg_conf:-0})
  decision_conf_count=$((decision_conf_count+1))
  rm -f "${time_out}"
 done

decision_quality_avg=$(python - <<PY
import sys
num=float(sys.argv[1]); den=int(sys.argv[2])
print(0 if den==0 else num/den)
PY
${decision_conf_total} ${decision_conf_count})

cat > "${VALIDATION_REPORT}" <<JSON
{
  "determinism": {
    "scenario": "${DETERMINISM_SCENARIO}",
    "results": [$(IFS=,; echo "${determinism_results[*]}")],
    "pass": ${determinism_pass}
  },
  "performance": {
    "scenarios": [$(IFS=,; echo "${perf_rows[*]}")]
  },
  "decision_quality": {
    "average_confidence": ${decision_quality_avg}
  },
  "notes": "Auto-generated by scripts/final-validation.sh"
}
JSON

echo "Validation report written to ${VALIDATION_REPORT}" >&2
