$project = "BotRunner"
$determinismScenario = "flipping_regression"
$perfScenarios = @("shoot_window_test", "ammo_pressure", "team_duel", "spawn_wave", "weapon_test", "moving_target", "flipping_test", "flipping_regression", "state_integrity_test", "swarm_retreat_test", "load_spike_test", "bad_payload", "reorder_drop", "many_actors", "duel", "loop", "respawn_loop", "demo")
$validationReport = "validation-report.json"

$determinismPass = $true
$determinismResults = @()

Write-Host "Validating determinism (100 seeds)..."
for ($seed = 1; $seed -le 100; $seed++) {
    $checksums = @()
    for ($run = 1; $run -le 2; $run++) {
        dotnet run --project $project -- --scenario $determinismScenario --seed $seed --quiet | Out-Null
        if (-not (Test-Path run-summary.json)) {
            $determinismPass = $false
            break
        }
        $checksum = python -c "import json; d=json.load(open('run-summary.json')); print(d.get('ChecksumMd5', 'MISSING'))"
        $checksums += $checksum
    }
    
    $uniqueCount = ($checksums | Select-Object -Unique).Count
    $passSeed = $uniqueCount -eq 1
    $determinismResults += "{`"seed`":$seed,`"pass`":$($passSeed.ToString().ToLower())}"
    if (-not $passSeed) { 
        Write-Host "Seed ${seed}: FAIL"
        $determinismPass = $false 
    }
    if (-not $determinismPass) { break }
    if ($seed % 10 -eq 0) { Write-Host "Checked ${seed} seeds..." }
}

Write-Host "Benchmarking performance..."
$perfRows = @()
$decisionConfTotal = 0.0
$decisionConfCount = 0

foreach ($scenario in $perfScenarios) {
    dotnet run --project $project -- --scenario $scenario --seed 1 --quiet | Out-Null
    if (-not (Test-Path run-summary.json)) {
        continue
    }
    
    # Use python to extract all needed fields at once
    $metrics = python -c "import json; d=json.load(open('run-summary.json')); print(str(d.get('TotalRuntimeSeconds', 0)) + '|' + '{:.2f}'.format(d.get('PerformanceMetrics', {}).get('PeakWorkingSetMb', 0)) + '|' + str(d.get('ActionPipeline', {}).get('AvgDecisionConfidence', 0)))"
    $parts = $metrics.Split('|')
    $timeVal = $parts[0]
    $memMb = $parts[1]
    $avgConf = $parts[2]
    
    $perfRows += "{`"scenario`":`"$scenario`",`"time_sec`":$timeVal,`"peak_mem_mb`":$memMb,`"avg_confidence`":$avgConf}"
    $decisionConfTotal += [double]$avgConf
    $decisionConfCount++
}

$decisionQualityAvg = if ($decisionConfCount -gt 0) { $decisionConfTotal / $decisionConfCount } else { 0 }

$report = @{
    determinism = @{
        scenario = $determinismScenario
        results = $determinismResults | ConvertFrom-Json
        pass = $determinismPass
    }
    performance = @{
        scenarios = $perfRows | ConvertFrom-Json
    }
    decision_quality = @{
        average_confidence = $decisionQualityAvg
    }
    notes = "Auto-generated by scripts/final-validation.ps1"
} | ConvertTo-Json -Depth 10

$report | Out-File -FilePath $validationReport -Encoding utf8
Write-Host "Validation report written to $validationReport"